name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  release:
    name: Create Release
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set release name
        
        run: |
          echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
          echo ::set-env name=RELEASE_NAME::$(echo ${GITHUB_REF:11})
          echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false

  publish:
    name: Publish Build
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish library
        env:
          bintrayUser: ${{ secrets.BINTRAY_USER }}
          bintrayApiKey: ${{ secrets.BINTRAY_API_KEY }}
        run: gradle bintrayUpload
